GRANT ALL PRIVILEGES ON actors TO WEB;
GRANT ALL PRIVILEGES ON addresses TO WEB;
GRANT ALL PRIVILEGES ON categories TO WEB;
GRANT ALL PRIVILEGES ON cities TO WEB;
GRANT ALL PRIVILEGES ON countries TO WEB;
GRANT ALL PRIVILEGES ON customers TO WEB;
GRANT ALL PRIVILEGES ON customers_history TO WEB;
GRANT ALL PRIVILEGES ON film_actors TO WEB;
GRANT ALL PRIVILEGES ON inventory TO WEB;
GRANT ALL PRIVILEGES ON orders TO WEB;
GRANT ALL PRIVILEGES ON order_items TO WEB;
GRANT ALL PRIVILEGES ON products TO WEB;
GRANT ALL PRIVILEGES ON reorders TO WEB;
GRANT ALL PRIVILEGES ON users TO WEB;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO WEB;
GRANT ALL PRIVILEGES ON SCHEMA public TO WEB;

REVOKE ALL PRIVILEGES ON flyway_schema_history FROM web;
